# permissions for end users to view celoblockchaintests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: celoblockchaintest-viewer-role
rules:
- apiGroups:
  - test.jcortejoso.com
  resources:
  - celoblockchaintests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.jcortejoso.com
  resources:
  - celoblockchaintests/status
  verbs:
  - get
